# Generated by Django 5.2.1 on 2025-05-20 22:49

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('syllable_count', models.IntegerField()),
                ('level', models.IntegerField()),
                ('connect_app', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SyllableBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllables', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=19), size=None)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllableconnect.wordbank', to_field='word')),
            ],
        ),
    ]
