# Generated by Django 5.2.1 on 2025-05-20 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllableconnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllablebank',
            name='word',
            field=models.ForeignKey(db_column='word', on_delete=django.db.models.deletion.CASCADE, to='syllableconnect.wordbank', to_field='word'),
        ),
    ]
