# Generated by Django 5.2.1 on 2025-06-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllableconnect', '0002_alter_syllablebank_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbank',
            name='jp_word',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
