# Generated by Django 5.2.1 on 2025-06-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllableconnect', '0003_wordbank_jp_word'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordbank',
            options={'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
        migrations.AddField(
            model_name='wordbank',
            name='image_filename',
            field=models.CharField(default=''),
        ),
    ]
