# Generated by Django 5.2.1 on 2025-06-16 23:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllableconnect', '0004_alter_wordbank_options_wordbank_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllablebank',
            name='sounds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), default=[], size=None),
        ),
    ]
