# Generated by Django 5.2.1 on 2025-06-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllableconnect', '0005_syllablebank_sounds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllablebank',
            old_name='sounds',
            new_name='audio',
        ),
    ]
