# Generated by Django 5.2.1 on 2025-06-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllableconnect', '0007_syllablebank_audio_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbank',
            name='audio_filename',
            field=models.CharField(default=''),
        ),
    ]
